### ISSUE TITLE
xxl-registry的几个问题

### ISSUE THREAD

**Issue by muwp** [xuxueli/xxl-registry#3]
您好，我今天看到了您写的这个项目,思路非常好，但是我想问下
1 各客户端向注册中心定期注册和发现为什么是设置成10s，1s，依据是什么？
2 如果在客户端机器达到一定规模的条件下这种不断的通过http向注册中心进行注册服务和获取服务是不是有影响？
3 现在这个注册中心有没有在线上运上 ？

**Comment by xuxueli** [comment]
你好，感谢支持！

1、客户端心跳与发现 10s 与 1s 为测试较优值，可自行调整。

2、注册中心天然支持集群与大规模部署，客户端大规模接入对注册中心没有太大影响，原因如下：
  - a、磁盘文件：服务注册、发现优先使用磁盘注册数据，客户端的密集请求会被磁盘这一层过滤拦截掉，并不会对DB产生太大压力。所以QPS非常高。
  - b、long polling：客户端基于 long polling 实时感知注册信息变更，仅在配置变更时拉取注册信息，请求密集较低。

3、有过线上运行：XXL-REGISTRY来源自XXL-RPC项目，且已经被内置在 “XXL-JOB、XXL-MQ” 项目里，而这几个项目均存在多个企业用户，可参考这些项目的接入登记文档。

**Comment by doctor-q** [comment]
你好，我简单的看了一下代码，这里有几个问题：
1. 能否无状态部署多副本，多副本之间读取文件怎么做到？
2. 注册服务较多会不会存在过多的文件碎片导致寻址慢，另外如果并发高会不会导致打开文件数过多？
3. http的主动pull模式会不会限制并发数，使用websocket之类的push技术不知道怎样？

**Comment by xuxueli** [comment]
@doctor-q 
1、目前无中心集群，支持无状态集群部署，依靠内部广播机器同步。
2、你好，服务发现可以结合提供的 long polling 服务配套使用，并不会频繁请求的，只会在服务变更时才会请求。
3、底层通过 long polling 实时感知服务变更，单机并发过万没有问题的。
