### ISSUE TITLE
有关参数校验的问题

### ISSUE THREAD

**Issue by muwp** [xuxueli/xxl-registry#5]
雪里，您好，注册中心的服务端和客户端都有参数校验，但有部分参数(如biz,env）都要求不小于4个字符，但是实际情况可能存在3个字符【如env=dev】等，能否把这两个参数的校验放宽点？

**Comment by xuxueli** [comment]
你好， 以优化处理，预计周末发布小版本一并发布。

**Comment by xuxueli** [comment]
@muwp 你好，已经推送了新Release版本 （https://github.com/xuxueli/xxl-registry/releases/tag/v1.0.1），该版本已经优化了上面提到的问题，可以下载确认。
