### ISSUE TITLE
集群节点实时同步服务注册信息，确保一致;存在疑问

### ISSUE THREAD

**Issue by BenXiangYangGuang** [xuxueli/xxl-registry#7]
您好,请教一个问题:
"集群节点实时同步服务注册信息，确保一致。" -----------这个不太明白请指教一下,我只发现了,服务端 admin 和客户端的通信的代码;没有发现集群admin之间的通信代码;集群之间通信,我猜想是同一个数据库实例,进行数据同步的.
望指教,谢谢!

XXL-REGISTRY内部通过广播机制，集群节点实时同步服务注册信息，确保一致。客户端借助 long pollong 实时感知服务注册信息，简洁、高效；

```
  /**
         * 一个广播线程:
         * 广播线程从registeryMessage表获取事件(registry,remove....)信息,然后同步注册器磁盘文件和处理客户端监控结果,并返回客户端;客户端结果,两种情况;1. 成功;2. 3个心跳时间(10s)超时返回;
         */
        /**
         * broadcase new one registry-data-file     (1/1s)  1 秒 执行一次; 采用thread 的方法;
         *
         * clean old message   (1/10s)  10 秒执行一次; 取余的方法;
         */
        executorService.execute(new Runnable() {
            @Override
            public void run() {
                while (!executorStoped) {
                    try {
                        // new message, filter readed
                        List<XxlRegistryMessage> messageList = xxlRegistryMessageDao.findMessage(readedMessageIds);
                        if (messageList!=null && messageList.size()>0) {
                            for (XxlRegistryMessage message: messageList) {
                                readedMessageIds.add(message.getId());

                                if (message.getType() == 0) {   // from registry、add、update、delete，ne need sync from db, only write

                                    XxlRegistry xxlRegistry = JacksonUtil.readValue(message.getData(), XxlRegistry.class);

                                    // process data by status
                                    if (xxlRegistry.getStatus() == 1) {
                                        // locked, not updated
                                    } else if (xxlRegistry.getStatus() == 2) {
                                        // disabled, write empty
                                        xxlRegistry.setData(JacksonUtil.writeValueAsString(new ArrayList<String>()));
                                    } else {
                                        // default, sync from db （aready sync before message, only write）
                                    }

                                    // 同步注册器磁盘文件 和处理客户端监控结果,并返回客户端;客户端结果,两种情况;1. 成功;2. 3个心跳时间(10s)超时返回
                                    setFileRegistryData(xxlRegistry);
                                }
                            }
                        }

                        // clean old message; 每 10 处理一个 registery message 数据;然后清除已经度过的messageId;
                        if ( (System.currentTimeMillis()/1000) % registryBeatTime ==0) {
                            xxlRegistryMessageDao.cleanMessage(registryBeatTime);
                            readedMessageIds.clear();
                        }
                    } catch (Exception e) {
                        if (!executorStoped) {
                            logger.error(e.getMessage(), e);
                        }
                    }
                    try {
                        TimeUnit.SECONDS.sleep(1);
                    } catch (Exception e) {
                        if (!executorStoped) {
                            logger.error(e.getMessage(), e);
                        }
                    }
                }
            }
        });
```

**Comment by Fi-Null** [comment]
executorService.execute(() -> {
            while (!executorStoped) {

                // align to beattime
                try {
                    long sleepSecond = registryBeatTime - (System.currentTimeMillis() / 1000) % registryBeatTime;
                    if (sleepSecond > 0 && sleepSecond < registryBeatTime) {
                        TimeUnit.SECONDS.sleep(sleepSecond);
                    }
                } catch (Exception e) {
                    if (!executorStoped) {
                        logger.error(e.getMessage(), e);
                    }
                }

                try {
                    // clean old registry-data in db
                    registryDataDao.cleanData(registryBeatTime * 3);

                    // sync registry-data, db + file
                    int offset = 0;
                    int pagesize = 1000;
                    List<String> registryDataFileList = new ArrayList<>();

                    List<Registry> registryList = registryDao.pageList(offset, pagesize, null, null, null);
                    while (registryList != null && registryList.size() > 0) {

                        for (Registry registryItem : registryList) {

                            // process data by status
                            if (registryItem.getStatus() == 1) {
                                // locked, not updated
                            } else if (registryItem.getStatus() == 2) {
                                // disabled, write empty
                                String dataJson = JsonUtil.toJson(new ArrayList<String>());
                                registryItem.setData(dataJson);
                            } else {
                                // default, sync from db
                                List<RegistryData> registryDataList = registryDataDao.findData(registryItem.getBiz(), registryItem.getEnv(), registryItem.getKey());
                                List<String> valueList = new ArrayList<>();
                                if (registryDataList != null && registryDataList.size() > 0) {
                                    for (RegistryData dataItem : registryDataList) {
                                        valueList.add(dataItem.getValue());
                                    }
                                }
                                String dataJson = JsonUtil.toJson(valueList);

                                // check update, sync db
                                if (!registryItem.getData().equals(dataJson)) {
                                    registryItem.setData(dataJson);
                                    registryDao.update(registryItem);
                                }
                            }

                            // sync file
                            String registryDataFile = setFileRegistryData(registryItem);

                            // collect registryDataFile
                            registryDataFileList.add(registryDataFile);
                        }


                        offset += 1000;
                        registryList = registryDao.pageList(offset, pagesize, null, null, null);
                    }

                    // clean old registry-data file
                    FileUtil.cleanFileRegistryData(registryDataFilePath, registryDataFileList);

                } catch (Exception e) {
                    if (!executorStoped) {
                        logger.error(e.getMessage(), e);
                    }
                }
                try {
                    TimeUnit.SECONDS.sleep(registryBeatTime);
                } catch (Exception e) {
                    if (!executorStoped) {
                        logger.error(e.getMessage(), e);
                    }
                }
            }
        });
这块代码是否有问题。清理了registryData数据，然后在用registryData和全量注册数据数据做比对。没比对上的数据都被删了，这块是不是有问题？

**Comment by xuxueli** [comment]
@BenXiangYangGuang 你好，是这个逻辑。
@Fi-Null 你好，清理的是过期数据，然后后面只有过期的数据才会删除。注册表数据每一条代表一个机器势力，万级别已经比较大了，基本不会出现海量数据情况。
